version: "3.9"
services:
  proxy:
    image: "caddy"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "57047:57047"
    depends_on:
      - server
      - redis
  server:
    build: server
    environment:
      - SITENAME=short.cxbt.kr
      - VT_APIKEY=3781b656df6a618bc05d9ec7b82895ce36cdffb462f8dc091341427ec473dcb6
      - TZ=Asia/Seoul
    depends_on:
      - redis
  redis:
    image: "redis"