version: "3.9"
services:
  proxy:
    image: "caddy"
    volumes:
      - ./proxy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "127.0.0.1:57047:57047"
    depends_on:
      - server
      - redis
  server:
    build: server
    environment:
      - SITENAME=URL Shortner
      - SERVER_URL=sh.cxbt.kr
      - VT_APIKEY=
      - TZ=Asia/Seoul
    depends_on:
      - redis
  redis:
    image: "redis"